# Generated by Django 3.2.2 on 2021-05-14 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='artist',
            field=models.CharField(default='unknown', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='show',
            name='date',
            field=models.CharField(default='unknown', max_length=80),
            preserve_default=False,
        ),
    ]
